_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

# set True to to ensure deterministic results
# makes training slower but gives more reproducibility than just setting seeds
deterministic: False
