# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: gpu_gtx_1080
    qos: default
    gres: gpu:1

    cpus_per_task: 4
    mem_gb: 10

    # 48 hours
    timeout_min: 2880

    # Do not requeue jobs
    max_num_timeout: 0

    array_parallelism: 8
